# Generated by Django 5.0.6 on 2026-05-31 21:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('request', 'Förfrågan'), ('planning', 'Planering'), ('active', 'Pågående'), ('completed', 'Avslutad'), ('invoiced', 'Fakturerad')], default='active', max_length=20)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('margin_alert_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit', models.CharField(default='st', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('550'), max_digits=8)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='AtaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('detected', 'Upptäckt'), ('pending_review', 'Väntar på granskning'), ('approved_internal', 'Godkänd internt'), ('sent_to_customer', 'Skickad till kund'), ('customer_approved', 'Godkänd av kund'), ('rejected', 'Avvisad')], default='detected', max_length=30)),
                ('trigger_type', models.CharField(choices=[('auto_no_matching_scope', 'Automatiskt (utanför kontrakt)'), ('manual', 'Manuellt')], default='manual', max_length=30)),
                ('notify_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ata_items', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('labor', 'Arbete'), ('material', 'Material')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit', models.CharField(default='st', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_ata', models.BooleanField(default=False)),
                ('ata_approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='api.project')),
            ],
        ),
    ]
