# Generated by Django 5.0.6 on 2026-06-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataitem',
            name='check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_atas', to='api.checkin'),
        ),
        migrations.AddField(
            model_name='ataitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_atas', to='api.materialusage'),
        ),
    ]
